### For loops

Whenever you want to apply any transformation to all elements in a list, you iterate through them with a `for` loop.

In [ ]:
names_list = ["Justine", "Anabel", "Karl"]

for name in names_list:
    print("Hello " + name + "!")

Hello Justine!
Hello Anabel!
Hello Karl!

Here, the word `name` could really be anything. It is just a placeholder that takes the value of each element in the for loop in every sucessive iteration, until the loop reaches the end of the list. Using a diferent name does not change the result:

In [ ]:
for dinosaur in names_list:
    print("Hello " + dinosaur + "!")

Hello Justine!
Hello Anabel!
Hello Karl!

If we wanted to store the resulting transformations of our loop into a new list, we would define an empty list first, and then `append()` all the elements as we iterate through the loop:

In [ ]:
greetings = []

for name in names_list:
    greetings.append("Hello " + name + "!")

In [ ]:
greetings

['Hello Justine!', 'Hello Anabel!', 'Hello Karl!']

**Exercise 1**. Create a List named `lower_names` with all the names of the students in your batch. Include name and surname, all in lowercase (like `john doe`).

In [ ]:
lower_names=["swathy subramanian", "henrik mann", "prachee frau", "hajra frau", "masoumeh frau", "yusuf mann", "yangtao mann", "trang frau"]

**Exercise 2** Create a new list `capital_names`  with both the names and surnames capitalized (like `John Doe`), by iterating through the first list with a `for` loop.

In [ ]:
lower_names=["swathy subramanian", "henrik mann", "prachee frau", "hajra frau", "masoumeh frau", "yusuf mann", "yangtao mann", "trang frau"]
capital_names=[n.title()for n in lower_names]
capital_names

['Swathy Subramanian',
 'Henrik Mann',
 'Prachee Frau',
 'Hajra Frau',
 'Masoumeh Frau',
 'Yusuf Mann',
 'Yangtao Mann',
 'Trang Frau']

### Conditions with `if`

Whenever you want to do something only if a condition is met, you will need an `if` statement. Let's say we want to greet people only if their name starts with "A". We will add a few more names to our list:

In [ ]:
names_list = ["Justine", "Amabel", "Karl", "Anna", "Lina", "Sergei", "Magnus", "Aurora"]

We can check one by one whether they start with "A" by selecting them from the list by their position using `[]`, and using the string method you already learned `starts_with()`:

In [ ]:
# Justine
print(names_list[0].startswith("A"))

# Amabel
print(names_list[1].startswith("A"))

False
True

These booleans, `True` or `False`, are exactly what `if` statements need. Whenever a condition is true, the code below the `if` statement runs; if the condition is false, the code is skipped and nothing happens:

In [ ]:
condition = True

if condition:
    print("yay")

yay

In [ ]:
condition = False

if condition:
    print("yay")

So we can now tie everything together:

- A for loop that iterates through the names.

- An `if` statment that checks whether the name starts with "A".

- A greeting.

In [ ]:
for name in names_list:
    if name.startswith("A"):
        print("Hello " + name + "!")

Hello Amabel!
Hello Anna!
Hello Aurora!

An `else` statement can be added if you want to do something with the elements that did not meet the condition. 

After the `if` and the `else` statements, you can continue coding normally â€”and the code will run independently of any conditions. Here, we print some text and a line break:

In [ ]:
for name in names_list:
    if name.startswith("A"):
        print("Hello " + name + "!")
    else:
        print("Bye " + name + "!")

Bye Justine!
Hello Amabel!
Bye Karl!
Hello Anna!
Bye Lina!
Bye Sergei!
Bye Magnus!
Hello Aurora!

Let's add a text that gets printed after each iteration of the loop, so it is clearer what's going on...

In [ ]:
for name in names_list:
    if name.startswith("A"):
        print("Hello " + name + "!")
    else:
        print("Bye " + name + "!")
    print("next iteration incoming... \n")

Bye Justine!
next iteration incoming...

Hello Amabel!
next iteration incoming...

Bye Karl!
next iteration incoming...

Hello Anna!
next iteration incoming...

Bye Lina!
next iteration incoming...

Bye Sergei!
next iteration incoming...

Bye Magnus!
next iteration incoming...

Hello Aurora!
next iteration incoming...

**Exercise 3** In the previous code, the "next iteration incoming..." text gets printed also for the last iteration, which might be confusing for whoever is reading the output of this code. Tweak the code so that this text only gets printed if we are not in the last element of our list.

**Tip**: it is totally normal if you don't know how to approach this exercise right away. You might need to use something we have not seeen in this lesson or the previous one. Google is your friend! If you are stuck for a long time (above 30 min), and have already tried many things, it's time to ask for help to your instructor.

In [ ]:
for name in names_list:
    if name.startswith("A"):
        print("Hello " + name + "!")
    else:
        print("Bye " + name + "!")
    if(name in names_list[:-1]):
      print("next iteration incoming... \n")
    else:
      print("end")

Bye Justine!
next iteration incoming...

Hello Amabel!
next iteration incoming...

Bye Karl!
next iteration incoming...

Hello Anna!
next iteration incoming...

Bye Lina!
next iteration incoming...

Bye Sergei!
next iteration incoming...

Bye Magnus!
next iteration incoming...

Hello Aurora!
end

### Bonus exercises

In [ ]:
# some lists and series to work with
import pandas as pd

car_brands = ["BMW", "Volkswagen", "Mercedes", "Ford", "Apple", "Toyota", 
              "Tesla", "Kia", "Porsche", "Mazda", "Honda", "Jaguar", 
              "Mitsubishi", "Audi", "Bentley", "Bugatti", "Chrisler"]

fibonacci = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 53, 89, 144]

characters = [["Harry", "Hermoine", "Ron"], 
              ["Daenerys Targaryen", "Jon Snow", "Tyrion Lannister", 
               "Cercei Lannister", "Arya Stark", "Sansa Stark"],
              ["Aragorn", "Gandalf", "Frodo", "Legolas", "Gollum", "Gimli"],
              ["Walter White", "Jesse Pinkman", "Gus Fring"]
             ]

sex_and_the_city = ["Carrie", "Samantha", "Charlotte", "Miranda"]

numbers = [1, 51, 59, 2, 95, 25, 28, 67, 14, 63, 84, 33, 56, 31, 54, 97, 77, 
            98, 46, 84, 6, 66, 86, 77, 69, 19, 77, 7, 76, 19, 59, 77, 28, 34, 
            94, 4, 45, 95, 41, 66, 5, 38, 35, 57, 84, 38, 94, 65, 45, 80, 83, 
            22, 12, 100, 52, 55, 31, 69, 29, 67, 4, 39, 87, 49, 81, 82, 96, 4, 
            85, 62, 90, 72, 70, 26, 29, 63, 48, 94, 58, 9, 49, 79, 33, 63, 41, 
            13, 90, 37, 31, 3, 11, 54, 56, 72, 91, 97, 2, 83, 82, 6]

numbers_ser = pd.Series(numbers)

**Exercise 4:** 

Implement the for loop that greets people for the `characters` list you used in the previous exercises. For now, do not include any condition â€”just say hello to every character. What do you need to do to iterate through lists inside a list?

In [ ]:
for c in characters:
  for i in c:
   print("Hello" + " "+ i +" "+"!")

Hello Harry !
Hello Hermoine !
Hello Ron !
Hello Daenerys Targaryen !
Hello Jon Snow !
Hello Tyrion Lannister !
Hello Cercei Lannister !
Hello Arya Stark !
Hello Sansa Stark !
Hello Aragorn !
Hello Gandalf !
Hello Frodo !
Hello Legolas !
Hello Gollum !
Hello Gimli !
Hello Walter White !
Hello Jesse Pinkman !
Hello Gus Fring !

**Exercise 5:** 

Tweak the code of the previous exercise to greet characters based on these conditions:

- If their name is composed of two words (Name Surname), the greeting should be "Hello Name, from the house of Surname".

- If their name is shorter than 6 characters, the greeting should replicate the last letter of the name as many times as needed until it reaches 6 characters.

In [ ]:
for c in characters:
 for i in c:
  name=i.split(" ")
  x=name[0]
  y=name[-1]
  if(len(i)>6):
   print("Hello" + " "+ str(x)+" "+"from the house of"+ " "+ str(y))
  else:
    print("Hello" + " "+ str(x)+" "+"from the house of"+ " "+str(i+i[-1:]))

Hello Harry from the house of Harryy
Hello Hermoine from the house of Hermoine
Hello Ron from the house of Ronn
Hello Daenerys from the house of Targaryen
Hello Jon from the house of Snow
Hello Tyrion from the house of Lannister
Hello Cercei from the house of Lannister
Hello Arya from the house of Stark
Hello Sansa from the house of Stark
Hello Aragorn from the house of Aragorn
Hello Gandalf from the house of Gandalf
Hello Frodo from the house of Frodoo
Hello Legolas from the house of Legolas
Hello Gollum from the house of Gollumm
Hello Gimli from the house of Gimlii
Hello Walter from the house of White
Hello Jesse from the house of Pinkman
Hello Gus from the house of Fring

**Exercise 6:** 


Take 50 samples(with replacement), each one of size 10 from `numbers_ser` series.

In [ ]:
numbers = [1, 51, 59, 2, 95, 25, 28, 67, 14, 63, 84, 33, 56, 31, 54, 97, 77, 
            98, 46, 84, 6, 66, 86, 77, 69, 19, 77, 7, 76, 19, 59, 77, 28, 34, 
            94, 4, 45, 95, 41, 66, 5, 38, 35, 57, 84, 38, 94, 65, 45, 80, 83, 
            22, 12, 100, 52, 55, 31, 69, 29, 67, 4, 39, 87, 49, 81, 82, 96, 4, 
            85, 62, 90, 72, 70, 26, 29, 63, 48, 94, 58, 9, 49, 79, 33, 63, 41, 
            13, 90, 37, 31, 3, 11, 54, 56, 72, 91, 97, 2, 83, 82, 6]

numbers_ser = pd.Series(numbers)
sample_with_replacement=[]
for i in range(50):
 sample_with_replacement.append(numbers_ser.sample(n=10,replace=True))
sample_with_replacement

[28    76
 77    94
 43    57
 72    70
 41    38
 13    31
 12    56
 42    35
 86    90
 97    83
 dtype: int64, 38    41
 52    12
 36    45
 2     59
 21    66
 52    12
 93    72
 95    97
 8     14
 50    83
 dtype: int64, 95    97
 10    84
 22    86
 70    90
 50    83
 46    94
 88    31
 62    87
 51    22
 55    55
 dtype: int64, 43    57
 89     3
 68    85
 61    39
 54    52
 21    66
 47    65
 29    19
 83    63
 0      1
 dtype: int64, 22    86
 30    59
 21    66
 24    69
 6     28
 37    95
 60     4
 98    82
 49    80
 25    19
 dtype: int64, 7     67
 8     14
 93    72
 31    77
 15    97
 89     3
 88    31
 43    57
 66    96
 65    82
 dtype: int64, 48     45
 96      2
 53    100
 49     80
 25     19
 79      9
 18     46
 89      3
 21     66
 58     29
 dtype: int64, 29    19
 51    22
 41    38
 23    77
 45    38
 71    72
 20     6
 47    65
 23    77
 79     9
 dtype: int64, 87    37
 25    19
 2     59
 37    95
 4     95
 76    48
 68    85
 95    97
 43    57
 96     2
 dtype: int64, 48    45
 29    19
 10    84
 20     6
 74    29
 25    19
 26    77
 58    29
 18    46
 82    33
 dtype: int64, 47    65
 9     63
 67     4
 83    63
 31    77
 0      1
 39    66
 39    66
 68    85
 69    62
 dtype: int64, 80    49
 75    63
 56    31
 54    52
 31    77
 13    31
 0      1
 39    66
 73    26
 93    72
 dtype: int64, 2     59
 15    97
 16    77
 23    77
 32    28
 73    26
 78    58
 49    80
 57    69
 36    45
 dtype: int64, 38    41
 45    38
 93    72
 18    46
 57    69
 62    87
 84    41
 62    87
 47    65
 94    91
 dtype: int64, 63    49
 78    58
 15    97
 37    95
 84    41
 72    70
 28    76
 38    41
 15    97
 8     14
 dtype: int64, 81    79
 92    56
 77    94
 25    19
 32    28
 50    83
 71    72
 14    54
 19    84
 70    90
 dtype: int64, 83    63
 77    94
 48    45
 52    12
 34    94
 83    63
 66    96
 68    85
 67     4
 60     4
 dtype: int64, 89      3
 46     94
 53    100
 63     49
 93     72
 91     54
 75     63
 5      25
 0       1
 62     87
 dtype: int64, 77    94
 58    29
 67     4
 39    66
 69    62
 32    28
 48    45
 75    63
 20     6
 72    70
 dtype: int64, 82    33
 48    45
 58    29
 52    12
 24    69
 32    28
 10    84
 48    45
 41    38
 97    83
 dtype: int64, 95    97
 21    66
 10    84
 30    59
 61    39
 1     51
 69    62
 98    82
 54    52
 2     59
 dtype: int64, 76    48
 57    69
 84    41
 88    31
 96     2
 90    11
 29    19
 96     2
 2     59
 73    26
 dtype: int64, 84    41
 91    54
 31    77
 58    29
 59    67
 13    31
 2     59
 97    83
 86    90
 33    34
 dtype: int64, 75    63
 76    48
 73    26
 48    45
 5     25
 75    63
 20     6
 1     51
 21    66
 30    59
 dtype: int64, 42    35
 36    45
 43    57
 17    98
 41    38
 38    41
 44    84
 63    49
 76    48
 84    41
 dtype: int64, 77    94
 55    55
 71    72
 85    13
 22    86
 34    94
 2     59
 5     25
 76    48
 81    79
 dtype: int64, 46    94
 85    13
 68    85
 58    29
 49    80
 5     25
 80    49
 32    28
 8     14
 24    69
 dtype: int64, 48    45
 16    77
 3      2
 21    66
 22    86
 7     67
 3      2
 52    12
 39    66
 97    83
 dtype: int64, 54    52
 74    29
 82    33
 46    94
 47    65
 70    90
 65    82
 66    96
 43    57
 55    55
 dtype: int64, 30     59
 79      9
 77     94
 88     31
 16     77
 53    100
 72     70
 13     31
 80     49
 80     49
 dtype: int64, 54    52
 5     25
 82    33
 84    41
 47    65
 57    69
 42    35
 81    79
 22    86
 81    79
 dtype: int64, 28     76
 4      95
 8      14
 65     82
 45     38
 53    100
 56     31
 16     77
 63     49
 79      9
 dtype: int64, 96     2
 31    77
 81    79
 55    55
 56    31
 8     14
 40     5
 61    39
 91    54
 9     63
 dtype: int64, 60     4
 3      2
 24    69
 64    81
 9     63
 60     4
 71    72
 22    86
 45    38
 80    49
 dtype: int64, 83    63
 10    84
 90    11
 85    13
 69    62
 75    63
 20     6
 10    84
 67     4
 45    38
 dtype: int64, 50    83
 27     7
 88    31
 46    94
 42    35
 48    45
 61    39
 26    77
 5     25
 94    91
 dtype: int64, 23    77
 69    62
 85    13
 3      2
 0      1
 71    72
 95    97
 67     4
 31    77
 74    29
 dtype: int64, 26    77
 25    19
 15    97
 63    49
 24    69
 33    34
 61    39
 28    76
 50    83
 2     59
 dtype: int64, 45    38
 81    79
 81    79
 13    31
 58    29
 43    57
 21    66
 88    31
 82    33
 65    82
 dtype: int64, 28    76
 85    13
 13    31
 62    87
 90    11
 81    79
 95    97
 46    94
 63    49
 68    85
 dtype: int64, 5     25
 72    70
 40     5
 79     9
 33    34
 72    70
 99     6
 44    84
 99     6
 31    77
 dtype: int64, 49    80
 15    97
 41    38
 96     2
 43    57
 32    28
 94    91
 96     2
 88    31
 91    54
 dtype: int64, 33    34
 96     2
 74    29
 49    80
 55    55
 36    45
 36    45
 50    83
 6     28
 3      2
 dtype: int64, 70    90
 11    33
 56    31
 87    37
 18    46
 98    82
 96     2
 17    98
 15    97
 50    83
 dtype: int64, 49    80
 92    56
 46    94
 81    79
 39    66
 29    19
 94    91
 34    94
 94    91
 37    95
 dtype: int64, 46    94
 87    37
 33    34
 23    77
 77    94
 95    97
 90    11
 3      2
 73    26
 81    79
 dtype: int64, 3      2
 77    94
 64    81
 88    31
 29    19
 36    45
 36    45
 82    33
 22    86
 5     25
 dtype: int64, 49    80
 78    58
 90    11
 92    56
 12    56
 49    80
 40     5
 78    58
 63    49
 38    41
 dtype: int64, 57    69
 16    77
 48    45
 81    79
 67     4
 33    34
 89     3
 95    97
 44    84
 77    94
 dtype: int64, 6     28
 1     51
 66    96
 30    59
 69    62
 59    67
 20     6
 27     7
 34    94
 62    87
 dtype: int64]